spring:
  application:
    name: rabbit

  data:
    r2dbc:
      repositories:
        enabled: true

  r2dbc:
    url: r2dbc:mysql://localhost:3306/rabbit
    database: rabbit
    port: 3306
    username: root
    password:

  codec:
    max-in-memory-size: 20MB

server:
  port: 18080
  ssl:
    key-store: keystore.p12
    key-store-password:
    key-store-type: PKCS12