spring:
  application:
    name: rabbit

  data:
    r2dbc:
      repositories:
        enabled: true

  r2dbc:
    url: r2dbc:mysql://localhost:3306/rabbit?useSSL=false&allowPublicKeyRetrieval=true
    database: rabbit
    port: 3306
    username: root
    password: P@ssw0rd

  codec:
    max-in-memory-size: 20MB

server:
  port: 18080
