spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      routes:
        - id: rabbit
          uri: https://localhost:18080
          predicates:
            - Path=/rabbit/**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}

server:
  port: 28080
  ssl:
    key-store: keystore.p12
    key-store-password:
    key-store-type: PKCS12