spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: rabbit
          uri: http://localhost:8080
          predicates:
            - Path=/rabbit/**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}

server:
  port: 28080
